version: '3.8'

services:
  api:
    container_name: mnemosyne-api
    restart: always
    env_file:
      - .env.${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./:/usr/src/mnemosyne-api
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - database
  database:
    image: postgres
    container_name: mnemosyne-db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - /:/data/postgres
