FROM node:18-alpine AS install-dependencies
WORKDIR /user/src/app
RUN npm install -g npm@latest
COPY package.json ./
RUN npm ci
COPY . .

FROM node:18-alpine AS create-build
WORKDIR /user/src/app
RUN npm install -g npm@latest
COPY --from=install-dependencies /user/src/app ./
RUN npm run build
USER node

FROM node:18-alpine AS run
WORKDIR /user/src/app
RUN npm install -g npm@latest
COPY --from=install-dependencies /user/src/app/node_modules ./node_modules
COPY --from=create-build /user/src/app/dist ./dist
COPY package.json ./
RUN npm prune --production
CMD ["npm", "run", "start:prod"]
