export enum Titles {
  HOME = 'home',
  TAC = 'tac',
  RESET_PASSWORD = 'resetPassword',
  REGISTRATION = 'registration',
  FORGOT_PASSWORD = 'forgotPassword',
  ACCOUNT_CONFIRMATION = 'accConfirm',
  COMPANY_ACC_CONFIRMATION = 'companyAccConfirm',
  COMPANY_MEMBER_ACC_CONFIRM = 'companyMemberAccConfirm',
  DASHBOARD = 'dashboard',
  SETTINGS = 'settings',
  RECOVER_ACCOUNT = 'recoverAccount',
  EMAIL_CHANGE_CONFIRMATION = 'emailChangeConfirm',
  LOGIN = 'login',
  CONTACT = 'contact',
  CREATE_PRODUCT = 'createProduct',
  PRODUCT = 'product',
  PRODUCT_NOT_FOUND = 'productNotFound',
  EDIT_PRODUCT = 'editProduct',
  MARKETPLACE = 'marketplace',
  FAVORITES = 'favorites',
  MARKETPLACE_USER = 'marketplaceUser',
  COMPANY_SETTINGS = 'companySettings',
  COMPANY_PRODUCTS_SETTINGS = 'companyProductsSettings',
  COMPANY = 'company'
}
