export enum ENDPOINTS_TYPE {
  REGISTRATION = 'registration',
  LOGIN = 'login',
  ACCOUNT_CONFIRMATION = 'account-confirmation',
  REGISTRATION_SEND_SMS_CODE = 'registration-send-sms-code',
  LOGIN_VERIFY_2FA = 'login-verify-2fa',
  REGISTRATION_VERIFY_2FA = 'registration-verify-2fa',
  REGISTRATION_VERIFY_MOBILE_PHONE = 'registration-verify-mobile-phone',
  LOGIN_VERIFY_MOBILE_PHONE = 'login-verify-mobile-phone',
  FORGOT_PASSWORD = 'forgot-password',
  RESET_USER_PASSWORD = 'reset-user-password',
  LOGIN_SEND_SMS_CODE = 'login-send-sms-code',
  REGISTRATION_GENERATE_2FA_QR = 'registration-generate-2fa-qr',
  LOGIN_GENERATE_2FA_QR = 'login-generate-2fa-qr',
  UPLOAD_USER_PHOTO = 'upload-user-photo',
  REFRESH = 'refresh',
  LOGOUT = 'logout',
  USER_INFO = 'user-info',
  USER_SECURITY = 'user-security'
}
