export enum Scopes {
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  ROLES_MANAGEMENT = 'ROLES_MANAGEMENT',
  COMPANY_INFORMATION_MANAGEMENT = 'COMPANY_INFORMATION_MANAGEMENT',
  PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT'
}
