FROM node:latest

WORKDIR /usr/src/mnemosyne-api

RUN npm i -g nest
RUN npm i -g @nestjs/cli

COPY ../../mnemosyne-web-interface/mnemosyne-api/package*.json ./

RUN npm install --force

COPY ../../mnemosyne-web-interface/mnemosyne-api/ .

RUN npm run build

CMD ["npm", "run", "start:prod"]
