openapi: 3.0.0
paths:
  /api/users/forgot-password:
    post:
      operationId: UsersController_forgotPassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordDto"
      responses:
        "201":
          description: ""
  /api/users/reset-user-password:
    post:
      operationId: UsersController_resetUserPassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResetUserPasswordDto"
      responses:
        "201":
          description: ""
  /api/users/upload-user-photo:
    post:
      operationId: UsersController_uploadUserPhoto
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadPhotoDto"
      responses:
        "201":
          description: ""
  /api/users/user-info:
    get:
      operationId: UsersController_getUserInfo
      parameters: []
      responses:
        "200":
          description: ""
    patch:
      operationId: UsersController_updateUserInfo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserInfoDto"
      responses:
        "200":
          description: ""
  /api/users/user-security:
    get:
      operationId: UsersController_getUserSecuritySettings
      parameters: []
      responses:
        "200":
          description: ""
  /api/confirmation-hash/account-confirmation:
    get:
      operationId: ConfirmationHashController_confirmAccount
      parameters:
        - name: confirmationHash
          required: true
          in: query
          schema:
            type: string
      responses:
        "200":
          description: ""
  /api/auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LogInUserDto"
      responses:
        "201":
          description: ""
  /api/auth/registration:
    post:
      operationId: AuthController_registration
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserDto"
      responses:
        "201":
          description: ""
  /api/auth/logout:
    get:
      operationId: AuthController_logout
      parameters: []
      responses:
        "200":
          description: ""
  /api/auth/refresh:
    get:
      operationId: AuthController_refreshTokens
      parameters: []
      responses:
        "200":
          description: ""
  /api/roles:
    post:
      operationId: RolesController_createRole
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRoleDto"
      responses:
        "201":
          description: ""
  "/api/roles/{value}":
    get:
      operationId: RolesController_getRoleByValue
      parameters:
        - name: value
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
  /api/roles/grant:
    post:
      operationId: RolesController_grantRole
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GrantRoleDto"
      responses:
        "201":
          description: ""
  /api/roles/revoke:
    post:
      operationId: RolesController_revokeRole
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RevokeRoleDto"
      responses:
        "201":
          description: ""
  /api/security/registration-generate-2fa-qr:
    get:
      operationId: SecurityController_registrationGenerateTwoFaQrCode
      parameters: []
      responses:
        "200":
          description: ""
  /api/security/login-generate-2fa-qr:
    post:
      operationId: SecurityController_loginGenerateTwoFaQrCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginGenerate2faQrDto"
      responses:
        "201":
          description: ""
  /api/security/generate-2fa-qr:
    get:
      operationId: SecurityController_generateTwoFaQrCode
      parameters: []
      responses:
        "200":
          description: ""
  /api/security/registration-verify-2fa:
    post:
      operationId: SecurityController_registrationVerifyTwoFaQrCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyTwoFaDto"
      responses:
        "201":
          description: ""
  /api/security/login-verify-2fa:
    post:
      operationId: SecurityController_loginVerifyTwoFaQrCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyTwoFaDto"
      responses:
        "201":
          description: ""
  /api/security/verify-2fa:
    post:
      operationId: SecurityController_verifyTwoFaQrCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyTwoFaDto"
      responses:
        "201":
          description: ""
  /api/security/disable-2fa:
    post:
      operationId: SecurityController_disableTwoFa
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DisableTwoFaDto"
      responses:
        "201":
          description: ""
  /api/security/registration-send-sms-code:
    post:
      operationId: SecurityController_registrationSendSmsCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationSendSmsCodeDto"
      responses:
        "201":
          description: ""
  /api/security/login-send-sms-code:
    post:
      operationId: SecurityController_loginSendSmsCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginSendSmsDto"
      responses:
        "201":
          description: ""
  /api/security/send-sms-code:
    post:
      operationId: SecurityController_sendSmsCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationSendSmsCodeDto"
      responses:
        "201":
          description: ""
  /api/security/get-sms-code:
    get:
      operationId: SecurityController_getSmsCode
      parameters: []
      responses:
        "200":
          description: ""
  /api/security/registration-verify-mobile-phone:
    post:
      operationId: SecurityController_registrationVerifyMobilePhone
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyMobilePhoneDto"
      responses:
        "201":
          description: ""
  /api/security/login-verify-mobile-phone:
    post:
      operationId: SecurityController_loginVerifyMobilePhone
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyMobilePhoneDto"
      responses:
        "201":
          description: ""
  /api/security/verify-mobile-phone:
    post:
      operationId: SecurityController_verifyMobilePhone
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyMobilePhoneDto"
      responses:
        "201":
          description: ""
  /api/security/verify-sms-code:
    post:
      operationId: SecurityController_verifySmsCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifySmsCode"
      responses:
        "201":
          description: ""
  /api/security/disable-phone:
    post:
      operationId: SecurityController_disablePhone
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DisableTwoFaDto"
      responses:
        "201":
          description: ""
  /api/security/delete-account:
    delete:
      operationId: SecurityController_deleteUserAccount
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteAccountDto"
      responses:
        "200":
          description: ""
  /api/security/change-password:
    patch:
      operationId: SecurityController_changePassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePasswordDto"
      responses:
        "200":
          description: ""
  /api/recovery/registration-generate-recovery-keys:
    post:
      operationId: RecoveryController_registrationGenerateRecoveryKeys
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateRecoveryKeysDto"
      responses:
        "201":
          description: ""
  /api/recovery/login-generate-recovery-keys:
    post:
      operationId: RecoveryController_loginGenerateRecoveryKeys
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginGenerateRecoveryKeysDto"
      responses:
        "201":
          description: ""
  /api/recovery/generate-recovery-keys:
    post:
      operationId: RecoveryController_generateRecoveryKeys
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateRecoveryKeysDto"
      responses:
        "201":
          description: ""
  /api/recovery/recover-account:
    post:
      operationId: RecoveryController_recoverUserAccount
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecoverAccountDto"
      responses:
        "201":
          description: ""
info:
  title: Mnemosyne
  description: Documentation of Mnemosyne API.
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  schemas:
    ForgotPasswordDto:
      type: object
      properties: {}
    ResetUserPasswordDto:
      type: object
      properties: {}
    UploadPhotoDto:
      type: object
      properties: {}
    UpdateUserInfoDto:
      type: object
      properties: {}
    LogInUserDto:
      type: object
      properties: {}
    CreateUserDto:
      type: object
      properties: {}
    CreateRoleDto:
      type: object
      properties: {}
    GrantRoleDto:
      type: object
      properties: {}
    RevokeRoleDto:
      type: object
      properties: {}
    LoginGenerate2faQrDto:
      type: object
      properties: {}
    VerifyTwoFaDto:
      type: object
      properties: {}
    DisableTwoFaDto:
      type: object
      properties: {}
    RegistrationSendSmsCodeDto:
      type: object
      properties: {}
    LoginSendSmsDto:
      type: object
      properties: {}
    VerifyMobilePhoneDto:
      type: object
      properties: {}
    VerifySmsCode:
      type: object
      properties: {}
    DeleteAccountDto:
      type: object
      properties: {}
    ChangePasswordDto:
      type: object
      properties: {}
    GenerateRecoveryKeysDto:
      type: object
      properties: {}
    LoginGenerateRecoveryKeysDto:
      type: object
      properties: {}
    RecoverAccountDto:
      type: object
      properties: {}
