export enum Confirmation {
  EMAIL_CHANGE = 'EMAIL_CHANGE',
  REGISTRATION = 'REGISTRATION',
  COMPANY_REGISTRATION = 'COMPANY_REGISTRATION',
  COMPANY_INVITATION = 'COMPANY_INVITATION',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD'
}
