export enum ProductSubcategory {
  KITCHEN = 'kitchen',
  BEDROOM = 'bedroom',
  BATHROOM = 'bathroom',
  DECORATION = 'decoration',
  HIKING = 'hiking',
  CYCLING = 'cycling',
  SWIMMING = 'swimming',
  FINANCE = 'finance',
  EQUIPMENT = 'equipment',
  BUSINESS_SOFTWARE = 'business_software',
  SERVICE = 'service',
  INGREDIENTS = 'ingredients',
  DISHES = 'dishes',
  COOKING_BOOKS = 'cooking_books',
  SPORTS_EQUIPMENT = 'sports_equipment',
  TRAIN = 'train',
  HARDWARE = 'hardware',
  SOFTWARE = 'software',
  IT_BOOKS = 'it_books'
}
