export enum ValidationError {
  WRONG_EMAIL_FORMAT = 'wrong-email-format',
  WRONG_IMAGE_FORMAT = 'user-photo-must-be-base64',
  WRONG_MFA_CODE_FORMAT = 'mfa-code-should-be-6-digit-code',
  WRONG_PHONE_CODE_FORMAT = 'phone-code-should-be-6-digit-code',
  WRONG_PASSWORD_FORMAT = 'wrong-password-format',
  WRONG_PHONE_FORMAT = 'wrong-phone-format',
  WRONG_TWO_FA_TOKEN_FORMAT = 'wrong-two-fa-token-format',
  WRONG_TWO_FA_TOKEN_LENGTH = 'wrong-two-fa-token-length',
  WRONG_LOCATION_FORMAT = 'wrong-location-format',
  WRONG_LOCATION_LENGTH = 'wrong-location-length',
  WRONG_COMPANY_FORMAT = 'wrong-company-format',
  WRONG_COMPANY_LENGTH = 'wrong-company-length',
  WRONG_FQDN = 'wrong-fqdn',
  WRONG_ROLE_VALUE = 'wrong-role-value',
  WRONG_FIRST_NAME_FORMAT = 'wrong-first-name-format',
  WRONG_FIRST_NAME_LENGTH = 'wrong-first-name-length',
  WRONG_LAST_NAME_FORMAT = 'wrong-last-name-format',
  WRONG_LAST_NAME_LENGTH = 'wrong-last-name-length',
  WRONG_PASSPHRASE_FORMAT = 'wrong-passphrase-format',
  WRONG_PASSPHRASE_LENGTH = 'wrong-passphrase-length',
  WRONG_REC_KEYS = 'corrupted-recovery-keys'
}
